### ISSUE TITLE
FluentValidationValidator gives error Method not found:FluentValidation.AssemblyScanner.FindValidatorsInAssembly

### ISSUE THREAD

**Issue by YeldosSakenov** [Blazored/FluentValidation#146]
I am building a single library type application for Api on .net core and a client on Blazor Server. [BlazorWASMByExample](https://jonhilton.net/img/BlazorWASMByExample/shared-validator.png)

On Api on .net Core I use FluentValidation.AspNetCore v 11.1.0
I use the same in my library.
I'm making Custom Validators.
On Blazor I use Blazored.FluentValidation 2.0.0, higher versions already conflict with Dll.
Checking on the API server works correctly, on the client it gives the following error:
`rror: System.MissingMethodException: Method not found: 'FluentValidation.AssemblyScanner FluentValidation.AssemblyScanner.FindValidatorsInAssembly(System.Reflection.Assembly)'.
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.GetValidatorForModel(IServiceProvider serviceProvider, Object model, Boolean disableAssemblyScanning)
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ValidateField(EditContext editContext, ValidationMessageStore messages, FieldIdentifier fieldIdentifier, IServiceProvider serviceProvider, Boolean disableAssemblyScanning, IValidator validator)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)`

The settings on the server are as follows:
` services.AddFluentValidationAutoValidation();
            services.AddScoped<IValidateEmail, ValidateEmail>();
            services.AddScoped<IValidator<RegisterViewModel>, SignUpValidator>();`
The following settings are on the client:
`  services.AddScoped<IValidateEmail, ValidateEmail>();
   services.AddScoped<IValidator<RegisterViewModel>, SignUpValidator>();`

Tell me what I'm doing wrong or is this a mistake?

**Comment by chrissainty** [comment]
The version of Blazored FluentValidation you're using doesn't support version 11 of FluentValidation. You need to use the latest preview release for version 11 support.

**Comment by YeldosSakenov** [comment]
Yes, you are right. I used FluentValidation.AspNetCore version 10.4.0 and Blazored.FluentValidation 2.0.3.
Thanks a lot.
