### ISSUE TITLE
Arrays missing Item indexer will result in NullReferenceException

### ISSUE THREAD

**Issue by zetterstrom** [Blazored/FluentValidation#34]
If the model contains arrays without Item indexer it will be a NullReferenceException at the ToFieldIdentifier method in  EditContextFluentValidationExtensions.cs.
The following line will be null in such a case:

```csharp
var prop = obj.GetType().GetProperty("Item");
```

Here is a simplified model that I use.

```csharp
eAvverka = new uppgifterTypeEAvverka
{                        
	AnmalanAnsokan = new uppgifterTypeEAvverkaAnmalanAnsokan
	{
		Allmant = new uppgifterTypeEAvverkaAnmalanAnsokanAllmant
		{                                
			Fastighet = new uppgifterTypeEAvverkaAnmalanAnsokanAllmantFastighet
			{
				FastNamn = "XXX",                                    
				Block = "19",
				Enhet = "1",
				KommunNamn = "YYY" //,                                    
			}                                
		},
		Avverkning = new uppgifterTypeEAvverkaAnmalanAnsokanAvverkning
		{			
			Andamal = 3,                                
			AndamalSpecified = true,
			OmlaggningAr = 2020,
			OmlaggningArSpecified = true,                                
			Foryngringmetoder = new uppgifterTypeEAvverkaAnmalanAnsokanAvverkningForyngringMetod[]
			{
				new uppgifterTypeEAvverkaAnmalanAnsokanAvverkningForyngringMetod
				{
					AntalTrad = 50,
					AntalTradSpecified = true,
					AntalHa = 10.4f,
					Metod = 1,
					TradslagSpecified = true,
					Tradslag = 0					
				}
			}
		}                            
	}                        
}
```

If there is a validation error in uppgifterTypeEAvverkaAnmalanAnsokanAvverkningForyngringMetod the exception will be thrown.

```csharp
blazor.server.js:19 [2020-08-12T08:38:23.027Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ToFieldIdentifier(EditContext editContext, String propertyPath)
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ValidateModel(EditContext editContext, ValidationMessageStore messages, IServiceProvider serviceProvider, Boolean disableAssemblyScanning, IValidator validator)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
e.log @ blazor.server.js:19
C @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
```

I had a hard time to find the bug until I downloaded the source code and made some debugging.

I fixed it with the following code, probably needs to be modified to be bulletproof but now the validation works for arrays.

```csharp
object newObj = null;
                if (nextToken.EndsWith("]"))
                {
                    // It's an indexer
                    // This code assumes C# conventions (one indexer named Item with one param)
                    nextToken = nextToken.Substring(0, nextToken.Length - 1);
                    
                    var prop = obj.GetType().GetProperty("Item");
                    
                    if(null != prop)
                    {
                        var indexerType = prop.GetIndexParameters()[0].ParameterType;
                        var indexerValue = Convert.ChangeType(nextToken, indexerType);
                        newObj = prop.GetValue(obj, new object[] { indexerValue });                        
                    }
                    else
                    {
                        // If there is no Item property
                        // Try to cast the object to array
                        object[] array = obj as object[];
                        if (array != null)
                        {
                            int indexerValue = Convert.ToInt32(nextToken);
                            newObj = array[indexerValue];
                        }
                        else
                        {
                            throw new InvalidOperationException($"Could not find indexer on object of type {obj.GetType().FullName}.");
                        }
                    }                                        
                }
```

Hosting model is Blazor Server.

**Comment by chrissainty** [comment]
Hi @zetterstrom, would you be happy to create a PR with a suggested fix for this issue?

**Comment by zetterstrom** [comment]
Yes, but I'm not so used with GIT :-). I thought that I should create a branch first and then the PR. However I'm not able to create a branch.

**Comment by zetterstrom** [comment]
Should not be closed, sorry!

**Comment by zetterstrom** [comment]
Any idea how I could create a PR?

**Comment by chrissainty** [comment]
Sorry @zetterstrom I missed this comment. To create a PR you need to fork the repo and then make the changes in your forked copy. Once you're done you can raise a PR from you fork to this repo. 

GitHub also provides several docs coving there above steps.
