### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by boomalator** [Blazored/FluentValidation#56]
**Describe the bug**
Unhandled exception in browser.

**To Reproduce**
While following the concepts in Chapter 5 of Blazor in action, I am getting this error:

```
[2021-03-29T21:44:03.980Z] Error: System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<FluentValidation.Results.ValidationFailure> FluentValidation.Results.ValidationResult.get_Errors()'.
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ValidateModel(EditContext editContext, ValidationMessageStore messages, IServiceProvider serviceProvider, Boolean disableAssemblyScanning, FluentValidationValidator fluentValidationValidator, IValidator validator)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.ValidateModel(EditContext editContext, ValidationMessageStore messages, IServiceProvider serviceProvider, Boolean disableAssemblyScanning, FluentValidationValidator fluentValidationValidator, IValidator validator)
   at Blazored.FluentValidation.EditContextFluentValidationExtensions.<>c__DisplayClass3_0.<AddFluentValidation>b__0(Object sender, ValidationRequestedEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.Forms.EditContext.Validate()
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
Frankly, I don't know where to look to find out why a method would be missing. :(

Here's the beginning of the Edit Form.

```
  <EditForm Model="@objNewPerson" OnValidSubmit="@HandleValidSubmit">
        <FluentValidationValidator />
        <FormSection Title="Personal Info">
```

Using `<DataAnnotationsValidator />` works fine (except I thought it would be easier to use fluent for the child records).

**Expected behavior**
No errors in JS console.
Validation error in markup ("Surname is required")

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**
Following the steps from Blazor in Action, with my own model, that includes a "child" record (Person and PhoneNumbers, rather than Trails and Steps).

**Comment by chrissainty** [comment]
Hi @boomalator. Could you provide a minimal repro of the issue please otherwise there is no way for me to understand where the problem might be.

**Comment by JeremySkinner** [comment]
Hi @chrissainty I suspect this is because the user is referencing FluentValidation 10.0 (probably a prerelease build) which changes the return type of `ValidationResult.Errors` from `IList<ValidationFailure>` to `List<ValidationFailure>`

 The nuget package doesn’t have an upper version limit for the dependency on FluentValidation, so nuget will allow users to upgrade FV to 10.0 even though it’s a major version release. You may want to add an upper bound to your package reference to prevent this going forward. I also realised I didn’t include this in the list of breaking changes for 10.0 so I’ll do that too.

**Comment by digitarenet** [comment]
I have the same issue after upgrade FluentValidation to v10.0, downgrading to v9.5.4 all works fine.

**Comment by chrissainty** [comment]
Thanks for the info @JeremySkinner. I'll get a limit added for the package and hopefully it should sort things out 👍

**Comment by JeremySkinner** [comment]
Sounds good. 10.0 is actually released now, I think the only thing you should need to do is recompile against it, but let me know if you run into any issues upgrading.
